language: java
rvm:
 - 2.2
 - jruby

addons:
  sonarcloud:
    organization: "blacktiago"
    token:
      secure: "dHa7Qo5aJARJhBqBJ5QYL7Ub1zRFVLqxh1HANjVwXKligsFRC5n6RAPDtiKHOt2crc7Khs/dD3+WNuIJEasaMhEavon20s/t1YhKcWB1rPdW1MjgOUUvUl5NGyMEe2+qABF5pLlSfRclsekZUH+NuuLOWwVnckrS0Xp4DQQ8nI00ljVwQr5n8e9UBcKCb8+nHvz1wOArEze8leACYyJEoSxoxIS+iXnQD8vDJ9j3C2yxsZUf17q4X6pWW3qx4i910+ttUjgfmFA3WysTAklrzRKFEQ82JT/2RZmEBQ2fcA98E8nZZgfQ9qt+uVTRJHm2Nazb/pW2vFobmI+AJNSBw+TqFtqCFIObaOIDAAY4OJbvFoBcF8MkVSumn59HpVs0rUjZ0pJvro+EuwUV+UwgMZ5Egp4aFvz5oTfmvtnskQuamoGGj5yTUzC+x+VKjusWOM0jC8Y9bGY6jX87fRjnvfyYosdtwCnZft7ygHKEaBI7lMGE4seh+kjHlxQ4K9GsZyiTn3N61/0qVrG5KUm0NcfGN+/WJCFTcUHFGrHtPzD9Lzqwx9yzm10XiRYY5TFEvqvCpX337UPAKBtoypDlh/ZPj0oDLgOLCxka3ObAIgaw5yJT/UF9fzebd4yFJVY97IkN3tZ9ooReevwi5brI1LS2rdAcN2fBpEFb63bHSWg="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=blacktiago_car-plate-predictor