language: java
rvm:
 - 2.2
 - jruby

addons:
  sonarcloud:
    organization: "blacktiago"
    token:
      secure: "nEx5qz3ax1m45zSnaoIVgeQ0Ue+Fc/D+Fj2AD4KXOWFR/i1z0edT/RHos/owVHIL2ObJo64rTMTFN1HWObl2GYh2HeQZ4QfGjeWm3ajROKXH+Rn2o2NriVOP5TmRWMahq0qMyX7ax2EHX3HfWGR07T9rxzYubs8BSRQXIzQze/F0zueZuzsKwbaPTdNekBCCIS/qC6/7HY0b6Ct1N48mlM3YALKg4duhE/1Bmc9U1dBWHZKghbhyfOQQw/QyLJDukeGYO+2IV/FWdCQuFbctrTuilKvm6C18o3WrH9yDK2Muow51fLG39EUKjuS01wBLdVf3w++ndim6fo2xYmk4LAndypAnnMcfjeub/p+Xq5rizq2IWwiva2SkS4kl0+jYQqJU5LZH0Io3NkeNIffUd2iBYzMIuZlJBNMK6zr6u/XpoIrZ2vSA+8YUWLloMGZf6kuaxGZN4lKhT+Hd+xenbgBxsLo6VPyYqFNHAea/8L080WbNTFfseBMq4iE4m9LceTNTm8KeX3sk2OTRSw4TssUmxVzYxKyR+0AnkL4Ergwz/bgUOCbn4vO2ClkeGDBoRVqklOKEJyz2VKS6ylyGDvPP1NMODllxyo26R8gCEwtqJ8+5ZZhQBz7Iq6jDgtwQPBf+4iX3lCeYEyOGmokpIEgPi6GZbsurXx52mirycBI="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=blacktiago_car-plate-predictor